In [1]:
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','_']]])

print(array.ndim)
print(array.shape)#(3, 3, 3) = 3 blocks, 3 rows, 3 columns
print(array[0, 0, 0])#this is multi dimensional indexing.in list we use chain indexing([][][]) but in numpy we use comma to separate the indexes of different dimensions.
print(array[2,2,1])

3
(3, 3, 3)
A
Z


In [2]:
word = array[0,2,1] + array[0,0,0] + array[0,1,0] + array[0,2,1] + array[0,2,2] 
print(word)

HADHI


In [3]:
array = np.array([['1','2','3','4'],
                  ['5','6','7','8'],
                  ['9','10','11','12'],
                  ['13','14','15','16']])
print(array.shape)#(4, 4) = 4 rows, 4 columns

# array[start:end:step] = slicing by rows
print(array[:3])#select everything from the start to index 3 but not including index 3
print(array[::-2])#select everything from the start to the end with a step of -2



(4, 4)
[['1' '2' '3' '4']
 ['5' '6' '7' '8']
 ['9' '10' '11' '12']]
[['13' '14' '15' '16']
 ['5' '6' '7' '8']]


In [4]:
#slicing by columns and rows
print(array[:,::2])#select everything from the start to the end with a step of 2
print(f'2nd = {array[0:2,0:2]}')



[['1' '3']
 ['5' '7']
 ['9' '11']
 ['13' '15']]
2nd = [['1' '2']
 ['5' '6']]


In [5]:
print(f'1st = {array[0:2,2:]}')
print(f'2nd = {array[2: , :2]}')

1st = [['3' '4']
 ['7' '8']]
2nd = [['9' '10']
 ['13' '14']]


# ARITHMETIC

In [6]:
#scalar arithmetic - linear algebra term(single value)
array = np.array([1,2,3])

print(array - 2, array * 3 , array / 4)
print(array ** 2)


[-1  0  1] [3 6 9] [0.25 0.5  0.75]
[1 4 9]


In [7]:
#vactorized algebra term
array = np.array([1.01,2.5,3.99])

print(np.sqrt(array))#to find sqrt of array elements
print(np.round(array))#to round array elements.to round down use floor() and use round up use ceil().
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
3.141592653589793


In [8]:
radii = np.array([1,2,3])#we convert each radius into area of circle

formula = np.pi * radii ** 2
print(np.round(formula))


[ 3. 13. 28.]


In [9]:
#element wise arithmetic.each operation is element by element b/w two arrays

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 / array2)
print(array1 - array2)
print(array1 * array2)
print(array1 ** array2)


[0.25 0.4  0.5 ]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]


In [10]:
#Comparison operators

scores = np.array([91,55,100,73,82,64])

print(scores > 60)
print(scores == 100)

scores[scores < 60] = 0
print(scores)

[ True False  True  True  True  True]
[False False  True False False False]
[ 91   0 100  73  82  64]


#### BROADCASTING

In [11]:
'''broadcasting allows numpy to perform operations on arrays with different
 shapes by virtually expanding dimensions so they
match the larger array's shape. '''
'''The dimensions should have same number 
                OR
    One of the dimensions has a size of 1.we read dimensions from right to left'''

array1 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])#2D array with 4 row and 4 column
array2 = np.array(          [[1],
                             [2],
                             [3],
                             [4]])#2D array with 4 rows but 1 column

print(array1.shape)
print(array2.shape)

print(array1 * array2)#we now have 4 rows and 4 cols


(4, 4)
(4, 1)
[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [12]:
array1 = np.array([[1,2,3,4,5,6,7,8,9,10]])#1 row 10 col
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])#10 row 1 col

print(array1.shape)
print(array2.shape)
print(array1 * array2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### aggregate functions

In [13]:
# Aggregate functions - summarize data and typically return a single value

array1 = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
#print(np.sum(array1))
#print(np.mean(array1))
#print(np.std(array1)) measure of spread within our data
#print(np.var(array1)) square of std
print(np.max(array1))
print(np.argmax(array1)) #position of maximum value
print(np.sum(array1, axis = 0))#0 will take col and return sum of cols

10
9
[ 7  9 11 13 15]


### FILTERING

In [14]:
'''filtering = Refers to the process of selecting elements
               that match a given condition'''

ages = np.array([[21,17,19,20,16,30,18,65],
                 [39,22,15,99,18,19,20,21]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[ages >= 65]
evens = ages[ages % 2 == 0]

print(teenagers)
print(adults)#boolean indexing will change the shape
print(seniors)
print(evens)

[17 16 15]
[21 19 20 30 18 39 22 18 19 20 21]
[65 99]
[20 16 30 18 22 18 20]


In [15]:
#using to preserve the shape of our array
adults = np.where(ages >= 18,ages , np.nan)#use -1 or np.nan or whatever..np.where(condition,array,fill_val)
print(adults)

[[21. nan 19. 20. nan 30. 18. 65.]
 [39. 22. nan 99. 18. 19. 20. 21.]]


### random numbers

In [16]:
rng = np.random.default_rng(seed=1)#setting a seed is useful for creating same results
print(rng.integers(low = 1,high = 101, size = (3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [17]:
np.random.seed(seed = 101)
print(np.random.uniform(-1,10,(2,2)))#uniform distribution(0 to 1)

[[ 4.6803849   5.27734346]
 [-0.68678351  0.88673822]]


In [18]:
rng = np.random.default_rng()

array = np.array([1,2,3,4,5])
rng.shuffle(array) #shuffle
print(array)

fruits = np.array(['apple','orange','banana','coconut','pineapple'])
fruit = rng.choice(fruits,size = 3) #choice
print(fruit)

[3 2 4 1 5]
['pineapple' 'orange' 'coconut']
